--[[
	Mod Tradutor para Minetest
	Copyright (C) 2017 BrunoMine (https://github.com/BrunoMine)
	
	Recebeste uma cópia da GNU Lesser General
	Public License junto com esse software,
	se não, veja em <http://www.gnu.org/licenses/>. 

	Esse mod apenas traduz o nome de itens de forma automatica
	facilitando a atualização do servidor para novas versões 
	dos mods que são de nativamente em outros idiomas
	
	Ao colocar itens de mods que ainda não estejam na lista
	lembre de adicionar o nome do mod nas dependencias (depends.txt)
	desse mod tradutor como dependencia opcional (exemplo meu_mod?)
  ]]

-- Lista de Traduções
local lista = {
	-- core
	{"air",							"Ar"},
	{"ignore",						"ignore"},

	-- boat
	{"boats:boat",						"Bote"},

	-- beds
	{"beds:bed",						"Cama Simples"},
	{"beds:fancy_bed",					"Cama Sofisticada"},

	-- bones
	{"bones:bones",						"Knochen"},
	
	-- bucket
	{"bucket:bucket_empty",					"Balde"},
	{"bucket:bucket_water",					"Balde com Agua"},
	{"bucket:bucket_river_water",				"Balde com Agua de Rio"},
	{"bucket:bucket_lava",					"Balde com Lava"},
	
	-- default
	-- craftitems	
	{"default:stick",					"Graveto"},
	{"default:paper",					"Papel"},
	{"default:book",					"Livro"},
	{"default:book_written",				"Livro usado"},
	{"default:coal_lump",					"Carvao"},
	{"default:tin_lump",					"Estanho Bruto"},
	{"default:iron_lump",					"Ferro Bruto"},
	{"default:copper_lump",					"Cobre Bruto"},
	{"default:mese_crystal",				"Cristal de Mese"},
	{"default:gold_lump",					"Ouro Bruto"},
	{"default:diamond",					"Diamante"},
	{"default:clay_lump",					"Argila Fresca"},
	{"default:tin_ingot",					"Barra de Estanho"},
	{"default:steel_ingot",					"Barra de Ferro"},
	{"default:copper_ingot",				"Barra de Cobre"},
	{"default:bronze_ingot",				"Barra de Bronze"},
	{"default:gold_ingot",					"Barra de Ouro"},
	{"default:mese_crystal_fragment",			"Fragmento de Mese"},
	{"default:clay_brick",					"Tijolinho de Argila"},
	{"default:scorched_stuff",				"Monturo de Cinzas"},
	{"default:obsidian_shard",				"Caco de Obsidiana"},
	{"default:skeleton_key",				"Chave Lisa"},
	{"default:key",						"Chave"},
	{"default:flint",					"Pederneira"},
	-- nodes
	{"default:stone",					"Pedra"},
	{"default:tinblock",					"Bloco de Estanho"},
	{"default:stone_block",					"Bloco de Pedra"},
	{"default:desert_stone",				"Pedra do Deserto"},
	{"default:desert_cobble",				"Pedregulho do Deserto"},
	{"default:stone_with_coal",				"Pedra com Carvao"},
	{"default:stone_with_tin",				"Pedra com Estanho"},
	{"default:stone_with_iron",				"Pedra com Ferro"},
	{"default:stone_with_copper",				"Pedra com Cobre"},
	{"default:stone_with_mese",				"Pedra com Mese"},
	{"default:stone_with_gold",				"Pedra com Ouro"},
	{"default:stone_with_diamond",				"Pedra com Diamante"},
	{"default:stonebrick",					"Tijolos de Pedra"},
	{"default:desert_stonebrick",				"Tijolos de Pedra do Deserto"},
	{"default:desert_stone_block",				"Bloco de Pedra do Deserto"},
	{"default:dirt_with_grass",				"Terra com Grama"},
	{"default:dirt_with_grass_footsteps",			"Terra com Grama Pisada"},
	{"default:dirt_with_dry_grass",				"Terra com Grama Seca"},
	{"default:dirt_with_snow",				"Terra com Neve"},
	{"default:dirt",					"Terra"},
	{"default:sand",					"Areia"},
	{"default:desert_sand",					"Areia do Deserto"},
	{"default:gravel",					"Cascalho"},
	{"default:sandstone",					"Arenito"},
	{"default:sandstone_block",				"Bloco de Arenito"},
	{"default:sandstonebrick",				"Tijolos de Arenito"},
	{"default:clay",					"Argila"},
	{"default:brick",					"Tijolos de Argila"},
	{"default:bush_leaves",					"Arbusto"},
	{"default:bush_stem",					"Caule de Arbusto"},
	{"default:tree",					"Arvore"},
	{"default:jungletree",					"Arvore Selvagem"},
	{"default:junglewood",					"Madeira Selvagem"},
	{"default:jungleleaves",				"Folhas de Arvore Selvagem"},
	{"default:junglesapling",				"Muda de Arvore Selvagem"},
	{"default:aspen_tree",					"Choupo"},
	{"default:aspen_wood",					"Madeira de Choupo"},
	{"default:aspen_leaves",				"Folhas de Choupo"},
	{"default:aspen_sapling",				"Muda de Choupo"},
	{"default:leaves",					"Folhas"},
	{"default:cactus",					"Cacto"},
	{"default:papyrus",					"Papiro"},
	{"default:bookshelf",					"Estante de Livros"},
	{"default:glass",					"Vidro"},
	{"default:fence_wood",					"Carca de Madeira"},
	{"default:gate_wood",					"Porteira de Madeira"},
	{"default:fence_pine_wood",				"Carca de Madeira de Pinheiro"},
	{"default:fence_junglewood",				"Carca de Madeira Selvagem"},
	{"default:fence_acacia_wood",				"Carca de Madeira de Acacia"},
	{"default:fence_aspen_wood",				"Carca de Madeira de Choupo"},
	{"default:rail",					"Trilho"},
	{"default:ladder",					"Escada de Madeira"},
	{"default:ladder_steel",					"Escada de Ferro"},
	{"default:wood",					"Madeira"},
	{"default:cloud",					"Nuvem"},
	{"default:water_flowing",				"Fluxo de Agua"},
	{"default:water_source",				"Fonte de Agua"},
	{"default:river_water_flowing",				"Fluxo de Agua de Rio"},
	{"default:river_water_source",				"Fonte de Agua de de Rio"},
	{"default:lava_flowing",				"Fluxo de Lava"},
	{"default:lava_source",					"Fonte de Lava"},
	{"default:torch",					"Tocha"},
	{"default:sign_wall",					"Letreiro de Madeira"},
	{"default:sign_wall_steel",				"Letreiro de Ferro"},
	{"default:chest",					"Bau"},
	{"default:chest_locked",				"Bau Trancado"},
	{"default:furnace",					"Forno"},
	{"default:furnace_active",				"Forno Aceso"},
	{"default:cobble",					"Pedregulho"},
	{"default:mossycobble",					"Pedregulho com Musgo"},
	{"default:coalblock",					"Bloco de Carvao"},
	{"default:steelblock",					"Bloco de Aco"},
	{"default:copperblock",					"Bloco de Cobre"},
	{"default:bronzeblock",					"Bloco de Bronze"},
	{"default:mese",					"Bloco de Mese"},
	{"default:goldblock",					"Bloco de Ouro"},
	{"default:diamondblock",				"Bloco de Diamante"},
	{"default:obsidian_glass",				"Vidro de Obsidiana"},
	{"default:obsidian",					"Obsidiana"},
	{"default:obsidianbrick",				"Tijolos de Obsidiana"},
	{"default:obsidian_block",				"Bloco de Obsidiana"},
	{"default:nyancat",					"Gato Nyan"},
	{"default:nyancat_rainbow",				"Rastro do Gato Nyan"},
	{"default:sapling",					"Muda de Arvore"},
	{"default:apple",					"Fruto"},
	{"default:dry_shrub",					"Arbustro Seco"},
	{"default:grass_1",					"Mato"},
	{"default:grass_2",					"Mato"},
	{"default:grass_3",					"Mato"},
	{"default:grass_4",					"Mato"},
	{"default:grass_5",					"Mato"},
	{"default:dry_grass_1",					"Mato Seco"},
	{"default:dry_grass_2",					"Mato Seco"},
	{"default:dry_grass_3",					"Mato Seco"},
	{"default:dry_grass_4",					"Mato Seco"},
	{"default:dry_grass_5",					"Mato Seco"},
	{"default:ice",						"Gelo"},
	{"default:snow",					"Neve"},
	{"default:snowblock",					"Bloco de Neve"},
	{"default:pine_needles",				"Agulhas de Pinheiro"},
	{"default:pine_sapling",				"Muda de Pinheiro"},
	{"default:pinetree",					"Pinheiro"},
	{"default:pinewood",					"Madeira de Pinheiro"},
	{"default:acacia_leaves",				"Folhas de Acacia"},
	{"default:acacia_sapling",				"Arvore de Acacia"},
	{"default:acacia_tree",					"Acacia"},
	{"default:acacia_wood",					"Madeira de Acacia"},
	{"default:acacia_bush_leaves",				"Folhas de Arbusto de Acacia"},
	{"default:acacia_bush_stem",				"Caule de Arbusto de Acacia"},
	{"default:meselamp",					"Lampada de Mese"},
	{"default:silver_sand",					"Areia Prateada"},
	{"default:coral_skeleton",				"Esqueleto de Coral"},
	{"default:coral_brown",					"Coral Marrom"},
	{"default:coral_orange",				"Coral Laranja"},
	{"default:silver_sand",					"Areia Prateada"},
	{"default:silver_sandstone",				"Arenito Prateado"},
	{"default:silver_sandstone_brick",			"Tijolos de Arenito Prateado"},
	{"default:silver_sandstone_block",			"Bloco de Arenito Prateado"},
	{"default:desert_sandstone",				"Arenito do Deserto"},
	{"default:desert_sandstone_brick",			"Tijolos de Arenito do Deserto"},
	{"default:desert_sandstone_block",			"Bloco de Arenito do Deserto"},
	{"default:mese_post_light",				"Poste de Luminaria Mese"},
	{"default:junglegrass",					"Arbusto Selvagem"},
	{"default:dirt_with_rainforest_litter",			"Terra com Lodo de Selva"},
	-- tools	
	{"default:pick_wood",					"Picareta de Madeira"},
	{"default:pick_stone",					"Picareta de Pedra"},
	{"default:pick_bronze",					"Picareta de Bronze"},
	{"default:pick_steel",					"Picareta de Ferro"},
	{"default:pick_mese",					"Picareta de Mese"},
	{"default:pick_diamond",				"Picareta de Diamante"},
	{"default:shovel_wood",					"Pa de Madeira"},
	{"default:shovel_stone",				"Pa de Pedra"},
	{"default:shovel_bronze",				"Pa de Bronze"},
	{"default:shovel_steel",				"Pa de Ferro"},
	{"default:shovel_mese",					"Pa de Mese"},
	{"default:shovel_diamond",				"Pa de Diamante"},
	{"default:axe_wood",					"Machado de Madeira"},
	{"default:axe_stone",					"Machado de Pedra"},
	{"default:axe_bronze",					"Machado de Bronze"},
	{"default:axe_steel",					"Machado de Ferro"},
	{"default:axe_mese",					"Machado de Mese"},
	{"default:axe_diamond",					"Machado de Diamante"},
	{"default:sword_wood",					"Porrete"},
	{"default:sword_stone",					"Porrete Cravejado"},
	{"default:sword_steel",					"Espada de Ferro"},
	{"default:sword_bronze",				"Espada de Bronze"},
	{"default:sword_mese",					"Espada de Mese"},
	{"default:sword_diamond",				"Espada de Diamante"},
	
	-- doors
	{"doors:door_wood",					"Porta de Madeira"},
	{"doors:door_steel",					"Porta de Ferro"},
	{"doors:door_glass",					"Porta de Vidro"},
	{"doors:door_obsidian_glass",				"Porta de Vidro de Obsidiana"},
	{"doors:trapdoor",					"Porta Rasteira"},
	{"doors:trapdoor_steel",				"Porta Rasteira de Ferro"},
	{"doors:gate_wood_closed",				"Porteira de Madeira"},
	{"doors:gate_junglewood_closed",			"Porteira de Madeira Selvagem"},
	{"doors:gate_acacia_wood_closed",			"Porteira de Madeira de Acacia"},
	{"doors:gate_pine_wood_closed",				"Porteira de Madeira de Pinheiro"},
	{"doors:gate_aspen_wood_closed",			"Porteira de Madeira de Choupo"},
	
	-- dye
	{"dye:white",						"Tinta Banca"},
	{"dye:grey",						"Tinta Cinza"},
	{"dye:dark_grey",					"Tinta Cinza Escuro"},
	{"dye:black",						"Tinta Preta"},
	{"dye:violet",						"Tinta Violeta"},
	{"dye:blue",						"Tinta Azul"},
	{"dye:cyan",						"Tinta Ciano"},
	{"dye:dark_green",					"Tinta Verde Escuro"},
	{"dye:green",						"Tinta Verde"},
	{"dye:yellow",						"Tinta Amarela"},
	{"dye:brown",						"Tinta Marrom"},
	{"dye:orange",						"Tinta Laranja"},
	{"dye:red",						"Tinta Vermelha"},
	{"dye:magenta",						"Tinta Magenta"},
	{"dye:pink",						"Tinta Rosa"},
	
	-- farming
	{"farming:straw",					"Fardo de Palha"},
	{"farming:soil",					"Solo"},
	{"farming:soil_wet",					"Solo Irrigado"},
	{"farming:cotton",					"Algodao"},
	{"farming:cotton_1",					"Algodao"},
	{"farming:cotton_2",					"Algodao"},
	{"farming:cotton_3",					"Algodao"},
	{"farming:cotton_4",					"Algodao"},
	{"farming:cotton_5",					"Algodao"},
	{"farming:sting",					"Linha de Algodao"},
	{"farming:hoe_wood",					"Enxada de Madeira"},
	{"farming:hoe_stone",					"Enxada de Pedra"},
	{"farming:hoe_steel",					"Enxada de Ferro"},
	{"farming:hoe_bronze",					"Enxada de Bronze"},
	{"farming:hoe_mese",					"Enxada de Mese"},
	{"farming:hoe_diamond",					"Enxada de Diamante"},
	{"farming:seed_wheat",					"Sementes de Trigo"},
	{"farming:seed_cotton",					"Sementes de Algodao"},
	{"farming:wheat",					"Trigo"},
	{"farming:wheat_1",					"Trigo"},
	{"farming:wheat_2",					"Trigo"},
	{"farming:wheat_3",					"Trigo"},
	{"farming:wheat_4",					"Trigo"},
	{"farming:wheat_5",					"Trigo"},
	{"farming:wheat_6",					"Trigo"},
	{"farming:wheat_7",					"Trigo"},
	{"farming:wheat_8",					"Trigo"},
	{"farming:flour",					"Farinha de Trigo"},
	{"farming:bread",					"Broa de Trigo"},
	
	-- fire
	{"fire:basic_flame",					"Fogo"},
	
	-- flowers
	{"flowers:dandelion_white",				"Dente-de-Leao Branco"},
	{"flowers:dandelion_yellow",				"Dente-de-Leao Amarelo"},
	{"flowers:geranium",					"Geranio"},
	{"flowers:rose",					"Rosa"},
	{"flowers:tulip",					"Tulipa"},
	{"flowers:viola",					"Violeta"},
	{"flowers:mushroom_red",				"Cogumelo Vermelho"},
	{"flowers:mushroom_brown",				"Cogumelo Marrom"},
	{"flowers:mushroom_spores_red",				"Esporos de Cogumelo Vermelho"},
	{"flowers:mushroom_spores_brown",			"Esporos de Cogumolo Marrom"},
	
	-- screwdriver
	{"screwdriver:screwdriver",				"Chave de Fenda"},

	-- stairs
	{"stairs:stair_wood",					"Degrau de Madeira"},
	{"stairs:stair_junglewood",				"Degrau de Madeira Selvagem"},
	{"stairs:stair_pinewood",				"Degrau de Madeira de Pinheiro"},
	{"stairs:stair_acacia_wood",				"Degrau de Madeira de Acacia"},
	{"stairs:stair_stone",					"Degrau de Pedra"},
	{"stairs:stair_stone_block",				"Degrau Bloco de Pedra"},
	{"stairs:stair_cobble",					"Degrau de Pedregulho"},
	{"stairs:stair_stonebrick",				"Degrau de Tijolos de Pedra"},
	{"stairs:stair_mossycobble",				"Degrau de Pedregulho com Musgo"},
	{"stairs:stair_sandstone",				"Degrau de Arenito"},
	{"stairs:stair_sandstone_block",			"Degrau de Bloco de Arenito"},
	{"stairs:stair_sandstonebrick",				"Degrau de Tijolos de Arenito"},
	{"stairs:stair_brick",					"Degrau de Tijolos de Argila"},
	{"stairs:stair_desert_stone",				"Degrau de Pedra do Deserto"},
	{"stairs:stair_desert_stone_block",			"Degrau de Bloco de Pedra do Deserto"},
	{"stairs:stair_desert_cobble",				"Degrau de Pedregulho do Deserto"},
	{"stairs:stair_desert_stonebrick",			"Degrau de Tijolos de Pedra do Deserto"},
	{"stairs:stair_obsidian",				"Degrau de Obsidiana"},
	{"stairs:stair_obsidian_block",				"Degrau de Bloco de Obsidiana"},
	{"stairs:stair_obsidianbrick",				"Degrau de Tijolos de Obsidiana"},
	{"stairs:stair_straw",					"Degrau de Palha"},
	{"stairs:stair_steelblock",				"Degrau de Bloco de Ferro"},
	{"stairs:stair_copperblock",				"Degrau de Bloco de Cobre"},
	{"stairs:stair_bronzeblock",				"Degrau de Bloco de Bronze"},
	{"stairs:stair_goldblock",				"Degrau de Bloco de Ouro"},
	{"stairs:stair_silver_sandstone",			"Degrau de Arenito Prateado"},
	{"stairs:stair_silver_sandstone_brick",			"Degrau de Tijolos de Arenito Prateado"},
	{"stairs:stair_silver_sandstone_block",			"Degrau de Bloco de Arenito Prateado"},
	{"stairs:stair_desert_sandstone",			"Degrau de Arenito do Deserto"},
	{"stairs:stair_desert_sandstone_brick",			"Degrau de Tijolos de Arenito do Deserto"},
	{"stairs:stair_desert_sandstone_block",			"Degrau de Bloco de Arenito do Deserto"},
	{"stairs:stair_snowblock",				"Degrau de Neve"},
	{"stairs:stair_ice",					"Degrau de Gelo"},
	
	{"stairs:slab_ice",					"Placa de Gelo"},
	{"stairs:slab_snowblock",				"Placa de Neve"},
	{"stairs:slab_silver_sandstone",			"Placa de Arenito Prateado"},
	{"stairs:slab_silver_sandstone_brick",			"Placa de Tijolos de Arenito Prateado"},
	{"stairs:slab_silver_sandstone_block",			"Placa de Bloco de Arenito Prateado"},
	{"stairs:slab_desert_sandstone",			"Placa de Arenito do Deserto"},
	{"stairs:slab_desert_sandstone_brick",			"Placa de Tijolos de Arenito do Deserto"},
	{"stairs:slab_desert_sandstone_block",			"Placa de Bloco de Arenito do Deserto"},
	{"stairs:slab_wood",					"Placa de Madeira"},
	{"stairs:slab_junglewood",				"Placa de Madeira Selvagem"},
	{"stairs:slab_pinewood",				"Placa de Madeira de Pinheiro"},
	{"stairs:slab_acacia_wood",				"Placa de Madeira de Acacia"},
	{"stairs:slab_stone",					"Placa de Pedra"},
	{"stairs:slab_stone_block",				"Placa Bloco de Pedra"},
	{"stairs:slab_cobble",					"Placa de Pedregulho"},
	{"stairs:slab_stonebrick",				"Placa de Tijolos de Pedra"},
	{"stairs:slab_mossycobble",				"Placa de Pedregulho com Musgo"},
	{"stairs:slab_sandstone",				"Placa de Arenito"},
	{"stairs:slab_sandstone_block",				"Placa de Bloco de Arenito"},
	{"stairs:slab_sandstonebrick",				"Placa de Tijolos de Arenito"},
	{"stairs:slab_brick",					"Placa de Tijolos de Argila"},
	{"stairs:slab_desert_stone",				"Placa de Pedra do Deserto"},
	{"stairs:slab_desert_stone_block",			"Placa de Bloco de Pedra do Deserto"},
	{"stairs:slab_desert_cobble",				"Placa de Pedregulho do Deserto"},
	{"stairs:slab_desert_stonebrick",			"Placa de Tijolos de Pedra do Deserto"},
	{"stairs:slab_obsidian",				"Placa de Obsidiana"},
	{"stairs:slab_obsidian_block",				"Placa de Bloco de Obsidiana"},
	{"stairs:slab_obsidianbrick",				"Placa de Tijolos de Obsidiana"},
	{"stairs:slab_straw", 					"Placa de Palha"},
	{"stairs:slab_steelblock",				"Placa de Bloco de Ferro"},
	{"stairs:slab_copperblock",				"Placa de Bloco de Cobre"},
	{"stairs:slab_bronzeblock",				"Placa de Bloco de Bronze"},
	{"stairs:slab_goldblock", 				"Placa de Bloco de Ouro"},

	-- tnt
	{"tnt:tnt",						"Explosivo TNT"},
	{"tnt:gunpowder",					"Polvora"},
	
	-- wool
	{"wool:white",						"Tecido Branco"},
	{"wool:grey",						"Tecido Cinza"},
	{"wool:dark_grey",					"Tecido Cinza Escuro"},
	{"wool:black",						"Tecido Preto"},
	{"wool:violet",						"Tecido Violeta"},
	{"wool:blue",						"Tecido Azul"},
	{"wool:cyan",						"Tecido Ciano"},
	{"wool:dark_green",					"Tecido Verde Escuro"},
	{"wool:green",						"Tecido Verde"},
	{"wool:yellow",						"Tecido Amarelo"},
	{"wool:brown",						"Tecido Marrom"},
	{"wool:orange",						"Tecido Laranja"},
	{"wool:red",						"Tecido Vermelho"},
	{"wool:magenta",					"Tecido Magenta"},
	{"wool:pink",						"Tecido Rosa"},
	
	-- fire
	{"fire:flint_and_steel",				"Pederneira e Ferro"},
	
	-- vessels
	{"vessels:glass_bottle",				"Pote de Vidro"},
	{"vessels:drinking_glass",				"Como de Vidro"},
	{"vessels:steel_bottle",				"Pote de Ferro"},
	{"vessels:glass_fragments",				"Cacos de Vidro"},
	{"vessels:shelf",					"Estante de Frascos"},

	-- xpanes
	{"xpanes:bar_flat",					"Painel de Barras de Ferro"},
	{"xpanes:pane_flat",					"Painel de Vidro"},
	
	-- walls
	{"walls:cobble",					"Muro de Pedregulho"},
	{"walls:mossycobble",					"Muro de Pedregulho com Musgo"},
	{"walls:desertcobble",					"Muro de Pedregulho do Deserto"},
	
	-- carts
	{"carts:cart",						"Carrinho (Agachar+Click para pegar)"},
	{"carts:powerrail",					"Trilho de Impulso"},
	{"carts:brakerail",					"Trilho de Freio"},
	
	
	-- creatures
	{"creatures:flesh",					"Carne"},
	{"creatures:meat",					"Carne Assada"},
	
	-- chicken
	{"creatures:chicken_flesh",				"Carne de Frango Crua"},
	{"creatures:chicken_meat",				"Carne de Frango Assada"},
	{"creatures:egg",					"Ovo de Galinha"},
	{"creatures:feather",					"Pluma"},
		
	-- sheep
	{"creatures:shears",					"Tesoura"},
	
	-- shields
	{"shields:shield_wood",					"Escudo de Madeira"},
	{"shields:shield_enhanced_wood",			"Escudo de Madeira Melhorado"},
	{"shields:shield_steel",				"Escudo de Ferro"},
	
	-- 3d_armor
	{"3d_armor:helmet_wood",				"Capacete de Madeira"},
	{"3d_armor:chestplate_wood",				"Peitoral de Madeira"},
	{"3d_armor:leggings_wood",				"Perneira de Madeira"},
	{"3d_armor:boots_wood",					"Botas de Madeira"},
	{"3d_armor:helmet_steel",				"Capacete de Ferro"},
	{"3d_armor:chestplate_steel",				"Peitoral de Ferro"},
	{"3d_armor:leggings_steel",				"Perneira de Ferro"},
	{"3d_armor:boots_steel",				"Botas de Ferro"},
	
	-- ItemFrames
	{"itemframes:frame",					"Mostruario"},
	
	-- Hardtorch
	{"hardtorch:torch",					"Tocha (usada)"},
	{"hardtorch:torch_on",					"Tocha Acesa"},
	{"hardtorch:lamp",					"Lamparina a Oleo"},
	{"hardtorch:lamp_on",					"Lamparina a Oleo Acesa"},
	{"hardtorch:oil",					"Oleo Combustivel"},
}

-- Efetuar traduções
for _, v in ipairs(lista) do
	if minetest.registered_items[v[1]] and v[2] ~= "" then
		minetest.override_item(v[1], {description = v[2]})
	end
end

